public class de.upb.sootup.instructions.ref.CaughtExceptionRef extends java.lang.Object
{

    public void <init>()
    {
        de.upb.sootup.instructions.ref.CaughtExceptionRef r0;

        r0 := @this: de.upb.sootup.instructions.ref.CaughtExceptionRef;

        specialinvoke r0.<java.lang.Object: void <init>()>();

        return;
    }

    void sth()
    {
        de.upb.sootup.instructions.ref.CaughtExceptionRef r0;
        java.lang.Exception r2, r3;
        java.io.PrintStream r4;

        r0 := @this: de.upb.sootup.instructions.ref.CaughtExceptionRef;

     label1:
        r2 = new java.lang.Exception;

        specialinvoke r2.<java.lang.Exception: void <init>()>();

        throw r2;

     label2:
        r3 := @caughtexception;

        r4 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke r4.<java.io.PrintStream: void println(java.lang.String)>("exception");

        return;

        catch java.lang.Exception from label1 to label2 with label2;
    }
}
